services:
  - type: web
    name: ruzmovie-backend
    env: node
    buildCommand: npm install
    startCommand: node backend/src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_DIALECT
        value: mysql
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 30d
      - key: FRONTEND_URL
        sync: false
      - key: RENDER_BACKEND_URL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: TEST_USER_PASSWORD
        sync: false
      - key: PORT
        value: 10000

databases: []